#include "channels.h"
#include "sigmastudio/prime_IC_1_PARAM.h"
#include "sigmastudio/prime_IC_1_REG.h"
using namespace DSPChannels;

#define NO_SEND { { 0, 0 } }
// clang-format off
Channel DSPChannels::spdif = {
    .fader = {MOD_SPDIF_IN_ALG0_TARGET_ADDR, MOD_SPDIF_IN_ALG1_TARGET_ADDR},
    .readback = {MOD_SPDIF_READBACK_ALG0_READBACKALGNEWSIGMA3001VALUE_ADDR, MOD_SPDIF_READBACK_ALG1_READBACKALGNEWSIGMA3002VALUE_ADDR},
    .stereoMode = MOD_SPDIF_STEREOMODE_STEREOMUXSIGMA300NS2INDEX_ADDR,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0000_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0101_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0200_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0301_ADDR }, 0, false },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0000_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0101_ADDR }, 0, true },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0200_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0201_ADDR }, 0, true },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0400_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0501_ADDR }, 0, false } },
    .type = CH_DIGITAL,
    .curStereoMode = STEREO,
    .faderPosition = 0,
    .balpan = 0,
    .mute = false,
    .usingInternalADC = false
};

Channel DSPChannels::bluetooth = {
    .fader = {MOD_BT_IN_ALG0_TARGET_ADDR, MOD_BT_IN_ALG1_TARGET_ADDR},
    .readback = {MOD_BT_READBACK_ALG0_READBACKALGNEWSIGMA3003VALUE_ADDR, MOD_BT_READBACK_ALG1_READBACKALGNEWSIGMA3004VALUE_ADDR},
    .stereoMode = MOD_BT_STEREOMODE_STEREOMUXSIGMA300NS3INDEX_ADDR,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0002_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0103_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0202_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0303_ADDR }, 0, false },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0002_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0103_ADDR }, 0, true },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0202_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0203_ADDR }, 0, true },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0402_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0503_ADDR }, 0, false } },
    .type = CH_DIGITAL,
    .curStereoMode = STEREO,
    .faderPosition = 0,
    .balpan = 0,
    .mute = false,
    .usingInternalADC = false
};

Channel DSPChannels::usb = {
    .fader = {MOD_USB_IN_ALG0_TARGET_ADDR, MOD_USB_IN_ALG1_TARGET_ADDR},
    .readback = {MOD_USB_READBACK_ALG0_READBACKALGNEWSIGMA3009VALUE_ADDR, MOD_USB_READBACK_ALG1_READBACKALGNEWSIGMA30010VALUE_ADDR},
    .stereoMode = MOD_USB_STEREOMODE_STEREOMUXSIGMA300NS4INDEX_ADDR,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0004_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0105_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0204_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0305_ADDR }, 0, false },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0004_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0105_ADDR }, 0, true },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0204_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0205_ADDR }, 0, true },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0404_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0505_ADDR }, 0, false } },
    .type = CH_DIGITAL,
    .curStereoMode = STEREO,
    .faderPosition = 0,
    .balpan = 0,
    .mute = false,
    .usingInternalADC = false
};

Channel DSPChannels::reverb = {
    .fader = {MOD_REVERB_FX_ALG0_TARGET_ADDR, MOD_REVERB_FX_ALG1_TARGET_ADDR},
    .readback = {MOD_REVERB_READBACK_ALG0_READBACKALGNEWSIGMA3007VALUE_ADDR, MOD_REVERB_READBACK_ALG1_READBACKALGNEWSIGMA3008VALUE_ADDR},
    .stereoMode = 0,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0006_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0107_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0206_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0307_ADDR }, 0, false },
               NO_SEND, NO_SEND,
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0406_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0507_ADDR }, 0, false } },
    .type = CH_FX,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = false
};

Channel DSPChannels::pitch = {
    .fader = {MOD_PITCH_FX_ALG0_TARGET_ADDR, MOD_PITCH_FX_ALG1_TARGET_ADDR},
    .readback = {MOD_PITCH_READBACK_READBACKALGNEWSIGMA30013VALUE_ADDR, 0},
    .stereoMode = 0,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0008_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0109_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0208_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0309_ADDR }, 0, false },
               NO_SEND, NO_SEND,
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0408_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0509_ADDR }, 0, false } },
    .type = CH_FX,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = false
};

Channel DSPChannels::master = {
    .fader = {MOD_MASTER_OUT_ALG0_TARGET_ADDR, MOD_MASTER_OUT_ALG1_TARGET_ADDR},
    .readback = {MOD_MASTER_READBACK_ALG0_READBACKALGNEWSIGMA3005VALUE_ADDR, MOD_MASTER_READBACK_ALG1_READBACKALGNEWSIGMA3006VALUE_ADDR},
    .stereoMode = MOD_MASTER_STEREOMODE_STEREOMUXSIGMA300NS1INDEX_ADDR,
    .sends = { NO_SEND, NO_SEND, NO_SEND, NO_SEND, NO_SEND },

    .type = CH_OUTPUT,
    .curStereoMode = STEREO,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = false
};

Channel DSPChannels::submix = {
    .fader = {MOD_SUBMIX_OUT_ALG0_TARGET_ADDR, MOD_SUBMIX_OUT_ALG1_TARGET_ADDR},
    .readback = {MOD_SUBMIX_READBACK_ALG0_READBACKALGNEWSIGMA30011VALUE_ADDR, MOD_SUBMIX_READBACK_ALG1_READBACKALGNEWSIGMA30012VALUE_ADDR},
    .stereoMode = MOD_SUBMIX_STEREOMODE_STEREOMUXSIGMA300NS5INDEX_ADDR,
    .sends = { NO_SEND, NO_SEND, NO_SEND, NO_SEND, NO_SEND },

    .type = CH_OUTPUT,
    .curStereoMode = STEREO,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = false
};

Channel DSPChannels::spdifo = {
    .fader = {MOD_SPDIFO_OUT_ALG0_TARGET_ADDR, MOD_SPDIFO_OUT_ALG1_TARGET_ADDR},
    .readback = {MOD_SPDIFO_READBACK_ALG0_READBACKALGNEWSIGMA30016VALUE_ADDR, MOD_SPDIFO_READBACK_ALG1_READBACKALGNEWSIGMA30017VALUE_ADDR},
    .stereoMode = MOD_SPDIFO_STEREOMODE_STEREOMUXSIGMA300NS6INDEX_ADDR,
    .sends = { NO_SEND, NO_SEND, NO_SEND, NO_SEND, NO_SEND },
    
    .type = CH_OUTPUT,
    .curStereoMode = STEREO,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = false
};

Channel DSPChannels::aux1 = {
    .fader = {MOD_AUX_IN_ALG0_TARGET_ADDR, MOD_AUX_IN_ALG1_TARGET_ADDR},
    .readback = {MOD_AUX1_2_READBACK_ALG0_READBACKALGNEWSIGMA30014VALUE_ADDR, 0},
    .stereoMode = 0,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0010_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0111_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0210_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0311_ADDR }, 0, false },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0006_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0107_ADDR }, 0, true },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0206_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0207_ADDR }, 0, true },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0410_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0511_ADDR }, 0, false } },
    
    .type = CH_ANALOG,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = false
};

Channel DSPChannels::aux2 = {
    .fader = {MOD_AUX_IN_ALG2_TARGET_ADDR, MOD_AUX_IN_ALG3_TARGET_ADDR},
    .readback = {MOD_AUX1_2_READBACK_ALG1_READBACKALGNEWSIGMA30015VALUE_ADDR, 0},
    .stereoMode = 0,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0012_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0113_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0212_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0313_ADDR }, 0, false },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0008_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0109_ADDR }, 0, true },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0208_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0209_ADDR }, 0, true },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0412_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0513_ADDR }, 0, false } },

    .type = CH_ANALOG,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = false
};

Channel DSPChannels::aux3 = {
    .fader = {MOD_AUX_IN_ALG4_TARGET_ADDR, MOD_AUX_IN_ALG5_TARGET_ADDR},
    .readback = {REG_ADC_READ0_IC_1_ADDR, 0},
    .stereoMode = 0,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0014_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0115_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0214_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0315_ADDR }, 0, false },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0010_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0111_ADDR }, 0, true },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0210_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0211_ADDR }, 0, true },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0414_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0515_ADDR }, 0, false } },

    .type = CH_ANALOG,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = true
};

Channel DSPChannels::aux4 = {
    .fader = {MOD_AUX_IN_ALG6_TARGET_ADDR, MOD_AUX_IN_ALG7_TARGET_ADDR},
    .readback = {REG_ADC_READ1_IC_1_ADDR, 0},
    .stereoMode = 0,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0016_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0117_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0216_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0317_ADDR }, 0, false },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0012_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0113_ADDR }, 0, true },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0212_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0213_ADDR }, 0, true },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0416_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0517_ADDR }, 0, false } },

    .type = CH_ANALOG,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = true
};

Channel DSPChannels::aux5 = {
    .fader = {MOD_AUX_IN_ALG8_TARGET_ADDR, MOD_AUX_IN_ALG9_TARGET_ADDR},
    .readback = {REG_ADC_READ2_IC_1_ADDR, 0},
    .stereoMode = 0,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0018_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0119_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0218_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0319_ADDR }, 0, false },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0014_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0115_ADDR }, 0, true },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0214_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0215_ADDR }, 0, true },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0418_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0519_ADDR }, 0, false } },

    .type = CH_ANALOG,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = true
};

Channel DSPChannels::aux6 = {
    .fader = {MOD_AUX_IN_ALG10_TARGET_ADDR, MOD_AUX_IN_ALG11_TARGET_ADDR},
    .readback = {REG_ADC_READ3_IC_1_ADDR, 0},
    .stereoMode = 0,
    .sends = { { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0020_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0121_ADDR }, 0, false },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0220_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0321_ADDR }, 0, false },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0016_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0117_ADDR }, 0, true },
               { { MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0216_ADDR, MOD_FX_SENDS_ALG0_NXNMIXALG1VOL0217_ADDR }, 0, true },
               { { MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0420_ADDR, MOD_OUTPUT_SENDS_ALG0_NXNMIXALG2VOL0521_ADDR }, 0, false } },

    .type = CH_ANALOG,
    .faderPosition = 0,
    .balpan = 0,
    .mute = true,
    .usingInternalADC = true
};
