#define RTA_SMOOTH_MULTIPLIER 0.4
#define DISPLAY_AUTO_DIMM_TIMEOUT 15000
#define UI_ACTIVITY_TIMEOUT 2000
#define EB_HOLD_TIME 400

#define BLUETOOTH_NAME "LTDA Prime"

#define DSP_I2C_ADDRESS 0x38
#define OLED_I2C_ADDRESS 0x3C